export const FETCH_ON_GET_NOTES_SUCCESS = "FETCH_ON_GET_NOTES_SUCCESS";
export const FETCH_ON_GET_NOTES_START = "FETCH_ON_GET_NOTES_START";
export const FETCH_ON_GET_NOTES_DATA_SUCCESS =
  "FETCH_ON_GET_NOTES_DATA_SUCCESS";
export const FETCH_ON_GET_NOTES_DATA_START = "FETCH_ON_GET_NOTES_DATA_START";
export const FETCH_ON_GET_NOTES_DATA_STOP = "FETCH_ON_GET_NOTES_DATA_STOP";
export const FETCH_ON_GET_ARCHIVE_START = "FETCH_ON_GET_ARCHIVE_START";
export const FETCH_ON_GET_ARCHIVE_SUCCESS = "FETCH_ON_GET_ARCHIVE_SUCCESS";
export const FETCH_ON_GET_NOTES_STOP = "FETCH_ON_GET_NOTES_STOP";
export const ON_CHANGE_FILTERS = "ON_CHANGE_FILTERS";
export const SET_EDIT_NOTE_STATE = "SET_EDIT_NOTE_STATE";
export const SET_ADD_NOTE_STATE = "SET_ADD_NOTE_STATE";
export const ON_SHOW_MODAL = "ON_SHOW_MODAL";
export const ON_HIDE_MODAL = "ON_HIDE_MODAL";
