export const FETCH_ON_GET_NOTES_SUCCESS = "FETCH_ON_GET_NOTES_SUCCESS";
export const FETCH_ON_GET_NOTES_START = "FETCH_ON_GET_NOTES_START";
export const FETCH_ON_GET_NOTES_STOP = "FETCH_ON_GET_NOTES_STOP";
