export const FETCH_ON_GET_NOTES_SUCCESS = "FETCH_ON_GET_NOTES_SUCCESS";
export const FETCH_ON_GET_NOTES_START = "FETCH_ON_GET_NOTES_START";
export const FETCH_ON_GET_NOTES_STOP = "FETCH_ON_GET_NOTES_STOP";
export const FETCH_ON_GET_NOTES_DATA_SUCCESS =
  "FETCH_ON_GET_NOTES_DATA_SUCCESS";
export const FETCH_ON_GET_NOTES_DATA_START = "FETCH_ON_GET_NOTES_DATA_START";
export const FETCH_ON_GET_NOTES_DATA_STOP = "FETCH_ON_GET_NOTES_DATA_STOP";
export const FETCH_ON_GET_ARCHIVE_START = "FETCH_ON_GET_ARCHIVE_START";
export const FETCH_ON_GET_ARCHIVE_SUCCESS = "FETCH_ON_GET_ARCHIVE_SUCCESS";
export const FETCH_ON_GET_ARCHIVE_STOP = "FETCH_ON_GET_ARCHIVE_STOP";
